name: johann
dependencies:
- conda=4.1.11=py35_0
- conda-env=2.5.2=py35_0
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- pycosat=0.6.1=py35_1
- pycrypto=2.6.1=py35_4
- python=3.5.2=0
- pyyaml=3.11=py35_4
- readline=6.2=2
- requests=2.10.0=py35_0
- ruamel_yaml=0.11.14=py35_0
- setuptools=23.0.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - boto3==1.4.0
  - botocore==1.4.56
  - click==6.6
  - decorator==4.0.10
  - docutils==0.12
  - dominate==2.2.1
  - entrypoints==0.2.2
  - flask==0.11.1
  - flask-bootstrap==3.3.7.0
  - flask-wtf==0.12
  - gunicorn==19.6.0
  - h5py==2.6.0
  - ipykernel==4.5.0
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - itsdangerous==0.24
  - jinja2==2.8
  - jmespath==0.9.0
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - keras==1.1.0
  - markupsafe==0.23
  - mistune==0.7.3
  - music21==3.1.0
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - notebook==4.2.3
  - numpy==1.11.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.7
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - python-dateutil==2.5.3
  - pyzmq==15.4.0
  - qtconsole==4.2.1
  - ruamel-yaml-==VERSION
  - s3transfer==0.1.4
  - scipy==0.18.1
  - simplegeneric==0.8.1
  - six==1.10.0
  - terminado==0.6
  - git+git://github.com/Theano/Theano.git
  - tornado==4.4.1
  - traitlets==4.3.0
  - visitor==0.1.3
  - wcwidth==0.1.7
  - werkzeug==0.11.11
  - widgetsnbextension==1.2.6
  - wtforms==2.1
